spring:
  application:
    name: NoteNestor

  datasource:
    url: jdbc:mysql://localhost:3306/enotes_db
    username: root
    password: 1234

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: kr494167@gmail.com
    password: cctl igzk kzze rbcr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  profiles:
    active: dev

file:
  upload:
    path: files/

# use for enhance --> add by Ai
springdoc:
  api-docs:
    path: /NoteNester-api-doc   # default, but explicit
  swagger-ui:
    path: /NoteNester-doc
    operations-sorter: method   # Sort GET, POST, PUT, DELETE order
    tags-sorter: alpha          # Sort tags alphabetically
    doc-expansion: none         # Collapse endpoints by default
    display-request-duration: true
    filter: true                 # Search bar in Swagger UI

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"  # Expose all actuator endpoints
        exclude: beans,loggers
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
